import { Metadata } from "next";
import { notFound } from "next/navigation";
import { supabase } from "@/lib/supabase";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { TrendingDown, CheckCircle, AlertTriangle } from "lucide-react";
import { PRICING_DATA } from "@/lib/pricing-data";

export async function generateMetadata({ params }: { params: Promise<{ id: string }> }): Promise<Metadata> {
  const { id } = await params;
  
  if (!process.env.NEXT_PUBLIC_SUPABASE_URL) {
    return {
      title: "AuditAI Report",
      description: "AI Tool Spend Optimization Report",
    };
  }

  const { data } = await supabase
    .from("audits")
    .select("company_name, results")
    .eq("id", id)
    .single();

  if (!data) return { title: "Report Not Found" };

  return {
    title: `${data.company_name} AI Spend Audit`,
    description: `We found $${data.results.totalSavings}/mo in potential savings for ${data.company_name}.`,
    openGraph: {
      title: `${data.company_name} | AuditAI Results`,
      description: `Optimizing AI Tool Stack - $${data.results.totalSavings}/mo savings identified.`,
    }
  };
}

export default async function ReportPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;

  let report = null;

  if (process.env.NEXT_PUBLIC_SUPABASE_URL) {
    const { data } = await supabase
      .from("audits")
      .select("*")
      .eq("id", id)
      .single();
    
    report = data;
  } else {
    // Mock fallback if DB is not connected
    report = {
      company_name: "Mock Company (No DB)",
      ai_summary: "This is a mock report since Supabase is not configured.",
      results: {
        totalCurrentSpend: 1000,
        totalOptimizedSpend: 800,
        totalSavings: 200,
        recommendations: [
          { toolId: "chatgpt_plus", action: "keep", reason: "Primary tool", potentialSavings: 0 }
        ]
      }
    };
  }

  if (!report) {
    notFound();
  }

  const { results, company_name, ai_summary } = report;

  return (
    <div className="container mx-auto px-4 py-12 max-w-4xl space-y-8">
      <div className="text-center space-y-2">
        <h1 className="text-3xl font-bold tracking-tight">{company_name}'s AI Audit</h1>
        <p className="text-muted-foreground">Generated by AuditAI</p>
      </div>

      <Card className="bg-primary/5 border-primary/20">
        <CardHeader className="pb-2">
          <CardTitle className="text-sm font-medium text-primary flex items-center gap-2">
            ✨ Executive Summary
          </CardTitle>
        </CardHeader>
        <CardContent>
          <p className="text-sm leading-relaxed">{ai_summary}</p>
        </CardContent>
      </Card>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        <Card className="bg-muted/20 border-border/40">
          <CardHeader className="pb-2">
            <CardTitle className="text-sm font-medium text-muted-foreground">Current Spend</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="text-3xl font-bold">${results.totalCurrentSpend}/mo</div>
          </CardContent>
        </Card>
        
        <Card className="bg-primary/10 border-primary/20">
          <CardHeader className="pb-2">
            <CardTitle className="text-sm font-medium text-primary">Optimized Spend</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="text-3xl font-bold text-primary">${results.totalOptimizedSpend}/mo</div>
          </CardContent>
        </Card>

        <Card className="bg-green-500/10 border-green-500/20">
          <CardHeader className="pb-2">
            <CardTitle className="text-sm font-medium text-green-500 flex items-center gap-2">
              <TrendingDown className="h-4 w-4" /> Potential Savings
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="text-3xl font-bold text-green-500">${results.totalSavings}/mo</div>
          </CardContent>
        </Card>
      </div>

      <div className="space-y-4">
        <h3 className="text-lg font-semibold">Recommendations</h3>
        <div className="space-y-3">
          {results.recommendations.map((rec: any, idx: number) => {
            const tool = PRICING_DATA[rec.toolId];
            const isPositive = rec.action === "keep";
            
            return (
              <Card key={idx} className={`border-l-4 ${isPositive ? 'border-l-green-500' : 'border-l-amber-500'}`}>
                <CardContent className="p-4 flex gap-4">
                  <div className="mt-1">
                    {isPositive ? (
                      <CheckCircle className="h-5 w-5 text-green-500" />
                    ) : (
                      <AlertTriangle className="h-5 w-5 text-amber-500" />
                    )}
                  </div>
                  <div>
                    <div className="flex items-center gap-2 mb-1">
                      <span className="font-semibold">{tool?.name || rec.toolId}</span>
                      <span className="text-xs uppercase tracking-wider px-2 py-0.5 rounded-full bg-muted font-medium">
                        {rec.action}
                      </span>
                    </div>
                    <p className="text-sm text-muted-foreground">{rec.reason}</p>
                  </div>
                </CardContent>
              </Card>
            );
          })}
        </div>
      </div>
    </div>
  );
}
